### ISSUE TITLE
Project_id is not parsed

### ISSUE THREAD

**Issue by JorTurFer** [pfnet-research/gcp-workload-identity-federation-webhook#12]
I'm using the helm chart to deploy the webhook. I have a service account like this:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-operator
  namespace: keda
  annotations:
    cloud.google.com/service-account-email: e2e-test-user@XXXX-XXXXX-XXXXX.iam.gserviceaccount.com
    cloud.google.com/workload-identity-provider: >-
      projects/XXXXXXXXXXXX/locations/global/workloadIdentityPools/jorge-aks/providers/jorge-aks
```
When I deploy a pod using the service account, I can see how an init container is properly injected and some things are done under the hood because I can see some files in `/var/run/secrets/gcloud/config`.
The problem is that the project_id isn't properly parsed IDK why (I'm a super noob with GCP), I can see these traces:
```
Created credential configuration file [/var/run/secrets/gcloud/config/federation.json].

Authenticated with external account credentials for: [e2e-test-user@XXXX-XXXXX-XXXXX.iam.gserviceaccount.com].
Your current project is [None].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID
```
The generated file doesn't contain the project_id:
```json
{
  "type": "external_account",
  "audience": "//iam.googleapis.com/projects/XXXXXXXXXXXX/locations/global/workloadIdentityPools/jorge-aks/providers/jorge-aks",
  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
  "token_url": "https://sts.googleapis.com/v1/token",
  "credential_source": {
    "file": "/var/run/secrets/sts.googleapis.com/serviceaccount/token"
  },
  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/e2e-test-user@XXXX-XXXXX-XXXXX.iam.gserviceaccount.com:generateAccessToken"
}
```
I thought this is normal, but I can see an error in KEDA : `GCE metadata "project/project-id" not defined` so I guess that the value is required, and it's missed. I can see that credentials.json downloaded from the console has a property `project_id` so I guess that's the issue.
TBH, IDK if I'm doing something wrong or that value is mandatory, but if it's optional, it'd be nice if we can provide it
