### ISSUE TITLE
Incorrect `defaultMode` for `gcp-iam-token` volume

### ISSUE THREAD

**Issue by JorTurFer** [pfnet-research/gcp-workload-identity-federation-webhook#15]
The `defaultMode` for the volume is still incorrect because it's 288, which isn't a valid value
```
- name: gcp-iam-token
      projected:
        sources:
          - serviceAccountToken:
              audience: sts.googleapis.com
              expirationSeconds: 86400
              path: token
        defaultMode: 288
```
