### ISSUE TITLE
Unable to run gcloud commands with non-root container user

### ISSUE THREAD

**Issue by hinewin** [pfnet-research/gcp-workload-identity-federation-webhook#48]
I'm experiencing an issue while attempting to execute gcloud commands with a non root container user. The issue appears to stem from restricted access to `/var/run/secrets/sts.googleapis.com/serviceaccount/..data/token`. This particular path needs to be accessible for gcloud commands to function properly. The problem persists even when I include the annotation `cloud.google.com/gcloud-run-as-user` in the service account.

**Comment by ordovicia** [comment]
Cloud you please share the details of your `gcp-workload-identity-federation-webhook` deployment (version, args, etc.) and ServiceAccounts and pods with which you are experiencing the issue, so that we can try to reproduce it?

**Comment by hinewin** [comment]
Webhook's version: `0.4.1`
I've verified the workload identity pool and provider are working properly and was able to access resources with a container that runs as root.
Using the same  working pool, provider and GSA, I've created a new KSA to support running a pod with a non-root container user and verified the correct ID for the non-root user.

Below is the KSA & Pod manifest file
```
# GSA has access to bucket `foo-gcs` and can read the secret file
# gcloud storage cat gs://foo-gcs/secret
# KSA Manifest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-foo
  namespace: default
  labels:
    app: wif-bar
  annotations:
    cloud.google.com/workload-identity-provider: "correct-identity-provider"
    cloud.google.com/service-account-email: "sa-foo@foo-bar-wif.iam.gserviceaccount.com"
    cloud.google.com/audience: "correct-audience"
    cloud.google.com/injection-mode: "gcloud"
    cloud.google.com/gcloud-run-as-user: "1001"


# Pod Manifest
---
apiVersion: v1
kind: Pod
metadata:
  name: sa-foo
  namespace: default
  labels:
    app: wif-bar
spec:
  serviceAccountName: sa-foo
  containers:
  - name: gcloud-kubectl
    image: foobar-image-with-non-root-user
    command: ["/bin/sh"]
    args: ["-c", "gcloud storage cat gs://foo-gcs/secret && while true; do echo 'keep alive'; sleep 10; done"]

```

logs from the following container return:
```
ERROR: gcloud crashed (PermissionError):   [Errno 13]  Permission denied: '/var/run/secrets/sts.googleapis.com/serviceacount/token'
```
